[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crypto = "0.5.0"
csv="1.1"
serde = { version = "1", features = ["derive"] }
sha2 = "0.10.6"
sha256 = "1.1.3"
